apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: deno-webserver-other
  name: deno-webserver-other
  namespace: other
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deno-webserver-other
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deno-webserver-other
    spec:
      containers:
      - image: deno-webserver-other:local
        imagePullPolicy: Never
        name: deno-webserver-other
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /srv/app/pvc
            name: logs

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
        - name: maria-db
          persistentVolumeClaim:
            claimName: maria-db
