apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
    app: deno-webserver
  name: deno-webserver
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deno-webserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deno-webserver
    spec:
      containers:
      - image: deno-webserver:local
        imagePullPolicy: Never
        name: deno-webserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /srv/app/pvc
            name: logs

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
        - name: maria-db
          persistentVolumeClaim:
            claimName: maria-db

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: deno-server
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/deno-server/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
