apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: maria-db
  name: maria-db
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: maria-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maria-db
    spec:
      containers:
        - image: mariadb:10.7
          imagePullPolicy: Always
          name: maria-db
          resources: {}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: db
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: maria-db
              mountPath: /var/lib/mysql

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
        - name: maria-db
          persistentVolumeClaim:
            claimName: maria-db

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: maria-db
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/maria-db/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: maria-db
spec:
  ports:
    - port: 3306
  selector:
    app: maria-db
